remote_theme: wet-boew/gcweb-jekyll
title: "Guardrails for Ransomware Prevention and Mitigation"
description: "Minimum guardrails for GC's ransomware prevention measures"
website: "https://canada-ca.github.io/guardrails-ransomware-prevention_mesures-de-protection-rancongiciels/"
